package com.springboot.MyTodoList.model;

import jakarta.persistence.*;

/*
 * ============================================================
 *  Entity: DocumentChunkTT
 *  Table:  DOCUMENT_CHUNK_TT
 * ============================================================
 *
 *  Stores individual text chunks extracted from uploaded documents.
 *  This is the persistent source of truth for the RAG BM25 index.
 *
 *  On application startup, RagIndexRebuildService reads all rows
 *  and reconstructs the Lucene index — so the index survives restarts
 *  even though Lucene writes to a temp directory.
 *
 *  Oracle DDL (created automatically by Hibernate ddl-auto=update):
 *    CREATE TABLE document_chunk_tt (
 *        chunk_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *        doc_id       NUMBER REFERENCES document_tt(doc_id) ON DELETE CASCADE,
 *        pj_id        NUMBER,
 *        chunk_index  NUMBER,
 *        chunk_text   CLOB
 *    );
 */
@Entity
@Table(name = "DOCUMENT_CHUNK_TT")
public class DocumentChunkTT {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CHUNK_ID")
    private long chunkId;

    /** FK to DOCUMENT_TT — cascade delete handled at DB level. */
    @Column(name = "DOC_ID", nullable = false)
    private long docId;

    /** Denormalized project ID for efficient per-project queries without JOIN. */
    @Column(name = "PJ_ID", nullable = false)
    private long pjId;

    /** Position of this chunk within its parent document (0-based). */
    @Column(name = "CHUNK_INDEX", nullable = false)
    private int chunkIndex;

    /** The extracted text content. Oracle CLOB handles chunks up to 4 GB. */
    @Lob
    @Column(name = "CHUNK_TEXT", nullable = false)
    private String chunkText;

    /** Original file name — stored here so rebuild doesn't need a JOIN to DOCUMENT_TT. */
    @Column(name = "DOC_NAME", length = 300)
    private String docName;

    public DocumentChunkTT() {}

    public DocumentChunkTT(long docId, long pjId, int chunkIndex, String chunkText, String docName) {
        this.docId      = docId;
        this.pjId       = pjId;
        this.chunkIndex = chunkIndex;
        this.chunkText  = chunkText;
        this.docName    = docName;
    }

    public long   getChunkId()               { return chunkId; }
    public long   getDocId()                 { return docId; }
    public void   setDocId(long docId)       { this.docId = docId; }
    public long   getPjId()                  { return pjId; }
    public void   setPjId(long pjId)         { this.pjId = pjId; }
    public int    getChunkIndex()            { return chunkIndex; }
    public void   setChunkIndex(int i)       { this.chunkIndex = i; }
    public String getChunkText()             { return chunkText; }
    public void   setChunkText(String t)     { this.chunkText = t; }
    public String getDocName()               { return docName; }
    public void   setDocName(String n)       { this.docName = n; }
}
